[package]
name = "silver_metrics"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
flux.workspace = true
flux-profiler.workspace = true
libc.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
flux-profiler = { workspace = true, features = ["test-util"] }

[lints]
workspace = true

[features]
perf = ["flux-profiler/perf"]
alloc-profile = ["flux-profiler/alloc-profile"]
