[package]
name = "silver_gossip"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
buffa.workspace = true
flux.workspace = true
flux-profiler.workspace = true
fxhash.workspace = true
hex.workspace = true
silver_common.workspace = true
silver_log.workspace = true
snap.workspace = true


[dev-dependencies]
criterion.workspace = true
hdrhistogram.workspace = true
pprof.workspace = true
rand.workspace = true
rand_core.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true

