[package]
name = "silver_storage"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
blst.workspace = true
c-kzg.workspace = true
flux.workspace = true
fxhash.workspace = true
libc.workspace = true
silver_common.workspace = true

[lints]
workspace = true

[dev-dependencies]
rand.workspace = true
