[package]
name = "silver_storage"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
blst.workspace = true
c-kzg.workspace = true
flux.workspace = true
fxhash.workspace = true
hex.workspace = true
silver_beacon_state_data.workspace = true
silver_common.workspace = true
silver_common_macros.workspace = true
silver_metrics.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
rand.workspace = true
