[package]
name = "silver_surfer"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crossterm.workspace = true
flux.workspace = true
hdrhistogram.workspace = true
libc.workspace = true
ratatui.workspace = true
silver_beacon_state_data.workspace = true
silver_common.workspace = true
silver_metrics.workspace = true
silver_network.workspace = true
silver_peer.workspace = true
silver_storage.workspace = true

[lints]
workspace = true
