[package]
name = "silver_beacon_api"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
flux.workspace = true
hex.workspace = true
mio.workspace = true
silver_beacon_state_data.workspace = true
silver_common.workspace = true
silver_httpcore.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json = "1.0.149"

[lints]
workspace = true
