[package]
name = "data_columns"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
c-kzg.workspace = true
flux.workspace = true
fxhash.workspace = true
libc.workspace = true
silver_common.workspace = true

[lints]
workspace = true
