mod attester_duties;
mod blocks;
mod config;
mod duties;
mod events;
mod head_verdict;
mod identity;
mod ids;
mod json;
mod node_status;
mod peers;
mod proposer_duties;
mod response;
mod router;
mod routes;
mod server;
mod statics;
mod sync_duties;
mod validator_api;
mod validators;

pub use node_status::{HeadStatus, NodeStatus};
pub use server::BeaconApi;
