[package]
name = "silver_beacon_state_data"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
silver_chain_spec.workspace = true
silver_ssz.workspace = true
flux.workspace = true
flux-profiler.workspace = true
blst.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
hex.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true
snap.workspace = true

[[bench]]
harness = false
name = "encode_checkpoint"

[lints]
workspace = true
