use flux::utils::ArrayVec;
use ring::digest;

use crate::types::B256;

pub fn sha256(data: &[u8]) -> B256 {
    let d = digest::digest(&digest::SHA256, data);
    let mut out = [0u8; 32];
    out.copy_from_slice(d.as_ref());
    out
}

fn hash_concat(a: &B256, b: &B256) -> B256 {
    let mut buf = [0u8; 64];
    buf[..32].copy_from_slice(a);
    buf[32..].copy_from_slice(b);
    sha256(&buf)
}

fn uint64_chunk(v: u64) -> B256 {
    let mut chunk = [0u8; 32];
    chunk[..8].copy_from_slice(&v.to_le_bytes());
    chunk
}

fn usize_chunk(v: usize) -> B256 {
    uint64_chunk(v as u64)
}

pub const ZERO_HASH: B256 = [0u8; 32];

/// Max SSZ depth we ever hit is 40 (VALIDATOR_REGISTRY_LIMIT = 2^40);
pub const ZERO_HASHES_LEN: usize = 48;

/// Stack of parked subtree roots keyed by height. Heights strictly decrease
/// from bottom to top.
type MerkleStack = ArrayVec<(u8, B256), ZERO_HASHES_LEN>;

/// Absorb a leaf, combining upward with any left-sibling already parked at
/// the same height.
fn merkle_push(stack: &mut MerkleStack, leaf: B256) {
    let mut cur = leaf;
    let mut h: u8 = 0;
    while let Some(&(top_h, top_root)) = stack.as_slice().last() {
        if top_h != h {
            break;
        }
        stack.pop();
        cur = hash_concat(&top_root, &cur);
        h += 1;
    }
    stack.push((h, cur));
}

/// Walk the parked stack up to `target_depth`, padding with zero subtrees
/// where no right-sibling is available.
fn merkle_finalize(mut stack: MerkleStack, target_depth: u8, zh: &[B256]) -> B256 {
    if stack.is_empty() {
        return zh[target_depth as usize];
    }
    let (first_h, first_root) = stack.pop().unwrap();
    let mut cur = first_root;
    let mut h = first_h;
    while h < target_depth {
        match stack.as_slice().last() {
            Some(&(top_h, top_root)) if top_h == h => {
                stack.pop();
                cur = hash_concat(&top_root, &cur);
            }
            _ => {
                cur = hash_concat(&cur, &zh[h as usize]);
            }
        }
        h += 1;
    }
    cur
}

/// zh[0] = ZERO_HASH; zh[i+1] = hash(zh[i] || zh[i]). Precompute once; pass
/// as a slice into the hash functions.
pub fn compute_zero_hashes() -> [B256; ZERO_HASHES_LEN] {
    let mut zh = [ZERO_HASH; ZERO_HASHES_LEN];
    for i in 1..ZERO_HASHES_LEN {
        zh[i] = hash_concat(&zh[i - 1], &zh[i - 1]);
    }
    zh
}

/// Merkleize with a fixed leaf count (power of two, for list limits).
pub fn merkleize_padded(chunks: &[B256], leaf_count: usize, zh: &[B256]) -> B256 {
    debug_assert!(leaf_count.is_power_of_two());
    debug_assert!(chunks.len() <= leaf_count);

    let target_depth = leaf_count.trailing_zeros() as u8;
    let mut stack = MerkleStack::new();
    for c in chunks {
        merkle_push(&mut stack, *c);
    }
    merkle_finalize(stack, target_depth, zh)
}

pub fn mix_in_length(root: &B256, length: usize) -> B256 {
    hash_concat(root, &usize_chunk(length))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn zh_table() -> [B256; ZERO_HASHES_LEN] {
        compute_zero_hashes()
    }

    fn hex_b32(s: &str) -> B256 {
        assert_eq!(s.len(), 64);
        let b = s.as_bytes();
        let n = |c: u8| -> u8 {
            match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                _ => panic!(),
            }
        };
        let mut out = [0u8; 32];
        for (i, byte) in out.iter_mut().enumerate() {
            *byte = (n(b[i * 2]) << 4) | n(b[i * 2 + 1]);
        }
        out
    }

    /// Anchor against the spec-published zero-subtree roots. Values below
    /// are the canonical zero-hashes generated by the recurrence
    /// `zh[i+1] = sha256(zh[i] || zh[i])`, zh[0] = [0u8; 32].
    /// Reproducible locally:
    ///   python3 -c 'import hashlib;x=bytes(32)
    ///   for _ in range(10): x=hashlib.sha256(x+x).digest(); print(x.hex())'
    #[test]
    fn zero_hashes_match_spec() {
        let zh = compute_zero_hashes();
        assert_eq!(zh[0], [0u8; 32]);
        let expected: &[(usize, &str)] = &[
            (1, "f5a5fd42d16a20302798ef6ed309979b43003d2320d9f0e8ea9831a92759fb4b"),
            (2, "db56114e00fdd4c1f85c892bf35ac9a89289aaecb1ebd0a96cde606a748b5d71"),
            (3, "c78009fdf07fc56a11f122370658a353aaa542ed63e44c4bc15ff4cd105ab33c"),
            (4, "536d98837f2dd165a55d5eeae91485954472d56f246df256bf3cae19352a123c"),
            (5, "9efde052aa15429fae05bad4d0b1d7c64da64d03d7a1854a588c2cb8430c0d30"),
            (6, "d88ddfeed400a8755596b21942c1497e114c302e6118290f91e6772976041fa1"),
            (7, "87eb0ddba57e35f6d286673802a4af5975e22506c7cf4c64bb6be5ee11527f2c"),
            (8, "26846476fd5fc54a5d43385167c95144f2643f533cc85bb9d16b782f8d7db193"),
            (9, "506d86582d252405b840018792cad2bf1259f1ef5aa5f887e13cb2f0094f51e1"),
            (10, "ffff0ad7e659772f9534c195c815efc4014ef1e1daed4404c06385d11192e92b"),
        ];
        for &(i, hex) in expected {
            assert_eq!(zh[i], hex_b32(hex), "zh[{i}]");
        }
    }

    #[test]
    fn uint64_chunk_encoding() {
        let c = uint64_chunk(0x0102030405060708);
        assert_eq!(c[0], 0x08);
        assert_eq!(c[7], 0x01);
        assert_eq!(c[8..], [0u8; 24]);
    }

    /// Element: 28 bytes of 0xFF + 4-byte LE int. Matches spec's e(v).
    fn e(v: u32) -> B256 {
        let mut chunk = [0xFF; 32];
        chunk[28..32].copy_from_slice(&v.to_le_bytes());
        chunk
    }

    fn z(i: usize) -> B256 {
        compute_zero_hashes()[i]
    }

    fn h(a: B256, b: B256) -> B256 {
        hash_concat(&a, &b)
    }

    #[test]
    fn spec_merkleize_vectors() {
        let zh = zh_table();
        let cases: Vec<(usize, usize, B256)> = vec![
            (0, 0, z(0)),
            (0, 1, z(0)),
            (1, 1, e(0)),
            (0, 2, h(z(0), z(0))),
            (1, 2, h(e(0), z(0))),
            (2, 2, h(e(0), e(1))),
            (0, 4, h(h(z(0), z(0)), z(1))),
            (1, 4, h(h(e(0), z(0)), z(1))),
            (2, 4, h(h(e(0), e(1)), z(1))),
            (3, 4, h(h(e(0), e(1)), h(e(2), z(0)))),
            (4, 4, h(h(e(0), e(1)), h(e(2), e(3)))),
            (0, 8, h(h(h(z(0), z(0)), z(1)), z(2))),
            (1, 8, h(h(h(e(0), z(0)), z(1)), z(2))),
            (2, 8, h(h(h(e(0), e(1)), z(1)), z(2))),
            (3, 8, h(h(h(e(0), e(1)), h(e(2), z(0))), z(2))),
            (4, 8, h(h(h(e(0), e(1)), h(e(2), e(3))), z(2))),
            (5, 8, h(h(h(e(0), e(1)), h(e(2), e(3))), h(h(e(4), z(0)), z(1)))),
            (6, 8, h(h(h(e(0), e(1)), h(e(2), e(3))), h(h(e(4), e(5)), h(z(0), z(0))))),
            (7, 8, h(h(h(e(0), e(1)), h(e(2), e(3))), h(h(e(4), e(5)), h(e(6), z(0))))),
            (8, 8, h(h(h(e(0), e(1)), h(e(2), e(3))), h(h(e(4), e(5)), h(e(6), e(7))))),
            (0, 16, h(h(h(h(z(0), z(0)), z(1)), z(2)), z(3))),
            (1, 16, h(h(h(h(e(0), z(0)), z(1)), z(2)), z(3))),
            (4, 16, h(h(h(h(e(0), e(1)), h(e(2), e(3))), z(2)), z(3))),
            (
                9,
                16,
                h(
                    h(h(h(e(0), e(1)), h(e(2), e(3))), h(h(e(4), e(5)), h(e(6), e(7)))),
                    h(h(h(e(8), z(0)), z(1)), z(2)),
                ),
            ),
        ];

        for (i, (count, limit, expected)) in cases.iter().enumerate() {
            let chunks: Vec<B256> = (0..*count as u32).map(e).collect();
            let limit_pow2 = if *limit == 0 { 1 } else { limit.next_power_of_two() };
            let result = merkleize_padded(&chunks, limit_pow2, &zh);
            assert_eq!(result, *expected, "case {i}: count={count} limit={limit}");
        }
    }
}
