[package]
name = "silver_control"
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
buffa.workspace = true
bytes.workspace = true
flux.workspace = true
raft.workspace = true
silver_chain_spec.workspace = true
silver_common.workspace = true
silver_gossip.workspace = true
silver_peer.workspace = true
fxhash.workspace = true
tracing.workspace = true

[build-dependencies]
buffa-build = "0.2.0"

[dev-dependencies]
silver_common = { workspace = true, features = ["test-util"] }
tempfile = "3"

[lints]
workspace = true
