name: test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-06-01

      - name: Install buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Download consensus-spec-tests
        run: make -C crates/beacon_state

      - name: Run tests
        run: cargo test --no-fail-fast
